### PR TITLE
fix: slippage flashing

### LINKED ISSUE #330: Slippage is flashing inside "Into" input field for a while when typing a value inside "From" input field on "Convert" page
**Description:**
Slippage is flashing (appears and disappears) inside "Into" input field for a while when typing a value inside "From" input field on "Convert" page.

**Prerequisites:**
- any synth/ERC-20 token in your wallet ("UNI" for example)

**Reproduction steps:**
1. Go to Kwenta "Convert" page (https://dev.kwenta.io/dashboard/convert)
2. Connect your wallet
3. Select any synth/ERC-20 token (for example "UNI") inside "From" drop-down
4. Type any value inside "From" input field and keep changing it

**Current behavior:**
- slippage is flashing (appears and disappears) each time you type anything inside "From" input field

**Expected behavior:**
- slippage shouldn't be flashing each time you type a value

**Screenshots:**

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.2.2
 - Browser: Chrome 89.0.4389.95

### PR DESCRIPTION
**Pull request by JChiaramonte7**
fixes #330

### CODE REVIEW

File: queries/1inch/use1InchQuoteQuery.ts [hunk 1]
```diff
@@ -24,6 +24,10 @@ const use1InchQuoteQuery = (
 			network?.id!
 		),
 		async () => {
+			if (Number(amount) === 0) {
+				return '';
+			}
```
Comment (JChiaramonte7) [inline queries/1inch/use1InchQuoteQuery.ts:29]: Quoting for 0 is a returns a real (garbage) quote from 1Inch API so needed this to prevent that case

File: sections/exchange/hooks/useExchange.tsx [hunk 2]
```diff
@@ -814,7 +814,8 @@ const useExchange = ({
 			}
 		}
 		return null;
-	}, [totalTradePrice, estimatedBaseTradePrice, txProvider]);
+		// eslint-disable-next-line
+	}, [estimatedBaseTradePrice, txProvider]);
```
Comment (JChiaramonte7) [inline sections/exchange/hooks/useExchange.tsx:818]: `totalTradePrice` in the dep array was causing bad slippage calcs while new `estimatedBaseTradePrice` data was loading
